### ISSUE TITLE
Imports appear wrong on AngryBots for version 0xc

### ISSUE THREAD

**Issue by KarlSchimpf** [WebAssembly/webassembly.github.io#19]
I've been trying to parse the AngryBots-0xc.wast or AngryBots12.wasm using wast2wasm and wasm2wast.  However, I've had no success parsing these using those tools.

**Comment by titzer** [comment]
Can you give an error trace here? AngryBots12.wasm parses in both Firefox and Chrome.

**Comment by KarlSchimpf** [comment]
branch: master
$ wabt/out/wasm2wast -o AngryBots12.wast AngryBots12.wasm 
error: @0x000257bd: unexpected opcode: 26 (0x1a)

branch: binary_0xc
$ wabt/out/wasm2wast -o AngryBots12.wast AngryBots12.wasm 
error: @0x000257bd: unexpected opcode: 26 (0x1a)

**Comment by s3ththompson** [comment]
Closed by #28
