### ISSUE TITLE
Toolchain Overview

### ISSUE THREAD

**Issue by s3ththompson** [WebAssembly/webassembly.github.io#23]
Document usage of the following tools:
- WABT
- Emscripten

Which intermediate formats are stable? Which are incidental?

**Comment by s3ththompson** [comment]
@adanilo do you want to take a stab at this one?

**Comment by adanilo** [comment]
Yeah, I'll have a go at it.

**Comment by s3ththompson** [comment]
Given current site architecture above, I think we should keep our existing Emscripten step-by-step guide and turn this toolchain overview into more of a discussion of other, advanced tools (like WABT) and how their intermediate formats can be used and built upon.

That way, beginning developers can just use Emscripten without worrying about the entire universe of tooling and advanced developers can view this page for more details and other tools.

**Comment by adanilo** [comment]
SGTM, will focus primarily on WABT in that case.

**Comment by kripken** [comment]
[Binaryen](https://github.com/WebAssembly/binaryen) might also make sense to discuss in a section for advanced developer tools (specifically, as a tool for compiler writers and/or people that want to further optimize a wasm file).

**Comment by adanilo** [comment]
Agreed, will add something for Binaryen

**Comment by adanilo** [comment]
Overview ready for review/merge in https://github.com/WebAssembly/webassembly.github.io/pull/40
